services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments
    ports:
      - "5432:5432"
    container_name: fiap-tech-challenge-fase-4-payments-db
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fiap

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiap-tech-challenge-fase-4-payments
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=payments
      - DB_HOST=db
      - DB_PORT=5432
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fiap

networks:
  fiap:
    driver: bridge
