{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lanchonete-payments-hpa
  labels:
    app: lanchonete-payments
    release: lanchonete
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lanchonete-payments
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
